Repository agdsn/hades, pull requests merged in 2020-11, with the labels that each got.

#90 Allow authentication for unknown MAC addresses
  templates/freeradius/mods-config/sql/main/postgresql/queries.conf
  templates/schema.sql.j2
  templates/schema_fdw.sql.j2
  tests/test-radius.bats
Labels: enhancement, hacktoberfest-accepted

#96 Debian packaging improvements
  LICENSE
  debian/control
  debian/copyright
  debian/hades.lintian-overrides
  debian/rules
  debian/source/format
  docs/source/conf.py
  locales/de/LC_MESSAGES/hades.po
  locales/hades.pot
Labels: enhancement

#97 Improve documentation
  docs/option_documenter.py
  docs/source/_static/custom.css
  docs/source/_static/logo.png
  docs/source/alternative-dns.rst
  docs/source/api/hades.agent.rst
  docs/source/api/hades.bin.rst
  docs/source/api/hades.common.rst
  docs/source/api/hades.config.rst
  docs/source/api/hades.deputy.rst
  docs/source/api/hades.portal.rst
  docs/source/api/hades.rst
  docs/source/cli.rst
  docs/source/components.rst
  docs/source/conf.py
  docs/source/configuration.rst
  docs/source/development.rst
  docs/source/docutils.conf
  docs/source/index.rst
  docs/source/networking.rst
  docs/source/replication.rst
  setup.py.in
  src/hades/agent/tasks.py
  src/hades/bin/agent.py
  src/hades/bin/check_database.py
  src/hades/bin/deputy.py
  src/hades/bin/export_options.py
  src/hades/bin/generate_config.py
  src/hades/bin/portal.py
  src/hades/bin/su.py
  src/hades/bin/vrrp_notify.py
  src/hades/common/cli.py
  src/hades/common/db.py
  src/hades/common/dbus.py
  src/hades/config/base.py
  src/hades/config/check.py
  src/hades/config/compute.py
  src/hades/config/options.py
  src/hades/config/sphinx.py
  src/hades/deputy/client.py
  src/hades/deputy/server.py
  src/hades/portal/__init__.py
  src/hades/portal/session.py
Labels: enhancement

#99 Upgrade to Debian 10 (Buster)
  MANIFEST.in
  configure.mk
  debian/control
  docker/Dockerfile
  docker/etc/apt/nodesource.gpg.key
  docker/etc/apt/sources.list
  docker/etc/postgresql-common/createcluster.conf
  requirements.txt
  scripts/control-database.sh.in
  src/hades/portal/session.py
  templates/freeradius/README.rst
  templates/freeradius/mods-available/cache
  templates/freeradius/mods-available/couchbase
  templates/freeradius/mods-available/date
  templates/freeradius/mods-available/dhcp_sqlippool
  templates/freeradius/mods-available/eap
  templates/freeradius/mods-available/inner-eap
  templates/freeradius/mods-available/ldap
  templates/freeradius/mods-available/linelog
  templates/freeradius/mods-available/moonshot-targeted-ids
  templates/freeradius/mods-available/mschap
  templates/freeradius/mods-available/ntlm_auth
  templates/freeradius/mods-available/otp
  templates/freeradius/mods-available/redis
  templates/freeradius/mods-available/rest
  templates/freeradius/mods-available/sqlippool
  templates/freeradius/mods-config/files/accounting
  templates/freeradius/mods-config/preprocess/huntgroups
  templates/freeradius/mods-config/python/example.py
  templates/freeradius/mods-config/python/radiusd.py
  templates/freeradius/mods-config/sql/ippool/postgresql/queries.conf
  templates/freeradius/mods-config/sql/main/postgresql/extras/update_radacct_group.sql
  templates/freeradius/mods-config/sql/main/postgresql/schema.sql
  templates/freeradius/mods-config/sql/moonshot-targeted-ids/postgresql/queries.conf
  templates/freeradius/mods-config/sql/moonshot-targeted-ids/postgresql/schema.sql
  templates/freeradius/panic.gdb
  templates/freeradius/policy.d/canonicalization
  templates/freeradius/policy.d/moonshot-targeted-ids
  templates/freeradius/proxy.conf
  templates/freeradius/radiusd.conf.j2
  templates/freeradius/radrelay.conf
  templates/freeradius/sites-available/abfab-tls
  templates/freeradius/sites-available/abfab-tr-idp
  templates/freeradius/sites-available/buffered-sql
  templates/freeradius/sites-available/copy-acct-to-home-server
  templates/freeradius/sites-available/decoupled-accounting
  templates/freeradius/sites-available/default
  templates/freeradius/sites-available/inner-tunnel
  templates/freeradius/sites-available/tls
  templates/freeradius/vmpsd.conf
Labels: enhancement

#74 Enable keepalived DBus interface
  conf/hades-auth-vrrp.service.in
  conf/hades-radius-vrrp.service.in
  conf/hades-unauth-vrrp.service.in
  conf/hades.busconfig.in
  configure.mk
  debian/control
  templates/auth-keepalived.conf.j2
  templates/radius-keepalived.conf.j2
  templates/unauth-keepalived.conf.j2
Labels: enhancement

#100 Improve configure script
  conf/hades.busconfig.in
  conf/hades.tmpfile.in
  configure.mk
  src/hades/common/cli.py
Labels: enhancement

#101 Hierarchical keepalived and netns templates
  conf/hades-auth-vrrp.service.in
  conf/hades-radius-vrrp.service.in
  conf/hades-unauth-vrrp.service.in
  templates/keepalived/auth.conf.j2
  templates/keepalived/common.conf.j2
  templates/keepalived/radius.conf.j2
  templates/keepalived/unauth.conf.j2
  templates/netns/auth/interfaces.j2
  templates/netns/common/interfaces.j2
  templates/netns/root/interfaces.j2
  templates/netns/unauth/interfaces.j2
  templates/radius-keepalived.conf.j2
  templates/unauth-keepalived.conf.j2
Labels: enhancement

#102 Improve unit files
  conf/config.py
  conf/hades-agent.service.in
  conf/hades-auth-alternative-dns.service.in
  conf/hades-auth-dhcp.service.in
  conf/hades-auth-netns-cleanup.service.in
  conf/hades-auth-netns.service.in
  conf/hades-auth-pristine-dns.service.in
  conf/hades-auth-vrrp.service.in
  conf/hades-cleanup.timer
  conf/hades-database.service.in
  conf/hades-deputy.service.in
  conf/hades-forced-refresh.timer
  conf/hades-radius-vrrp.service.in
  conf/hades-radius.service.in
  conf/hades-refresh.timer
  conf/hades-root-netns-cleanup.service.in
  conf/hades-root-netns.service.in
  conf/hades-root-vrrp.service.in
  conf/hades-unauth-dns.service.in
  conf/hades-unauth-http.service.in
  conf/hades-unauth-netns-cleanup.service.in
  conf/hades-unauth-netns.service.in
  conf/hades-unauth-portal.service.in
  conf/hades-unauth-vrrp.service.in
  conf/hades.busconfig.in
  conf/hades.default
  conf/hades.service
  conf/hades.target
  conf/hades.tmpfile.in
  configure.mk
  debian/hades.install
  docs/source/index.rst
  scripts/check-services.sh.in
  scripts/package-setup.sh.in
  src/hades/agent/tasks.py
  src/hades/bin/vrrp_notify.py
  src/hades/config/options.py
  templates/keepalived/root.conf.j2
  templates/netns/root/interfaces.j2
  templates/unbound-common.j2
Labels: bug, enhancement
